### ISSUE TITLE
Build of docker failing due to pgp package download issues

### ISSUE THREAD

**Issue by kopp** [kopp/build-aur-packages#2]
Currently, downloading the keys necessary to install the "aurutils" often fails depending on the keyserver (or maybe depending on the key)?

**Comment by kopp** [comment]
@xee5ch : Just so that you know that there are these issues :/

**Comment by xee5ch** [comment]
@kopp, thanks for noticing, but how exactly did you notice the errors when I ran my fork, as it is customized slightly. Did Github send you a notification message?

It seems that might be an occassional timeout, or maybe not, but I was then getting [errors about permissions on the `/workspace` directory](https://github.com/xee5ch/aurci2/runs/3098181757?check_suite_focus=true), [even though my non-root user should have that access](https://github.com/xee5ch/build-aur-packages/commit/935876a2109a572d80433ea632fbf22748e5ef4c#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R20), so I have to spend more time looking.

Thanks for your interest, help, and encouragement though!

**Comment by kopp** [comment]
Quite simple: I saw that you forked my repo and I know that I have 
spurious failures in my own build. Looks like we have different problems, 
though.

In your case it may be related to a glibc issue (which is known to bring 
permission issues). The changes of the 
https://github.com/kopp/build-aur-packages/releases/tag/v1-glibcfix tag 
fixed those for me.

19.07.2021 04:00:09 Al S ***@***.***>:

**Comment by xee5ch** [comment]
Well, you weren't kidding. I backtracked through your comments with SickCodes and ServerFault and finally [the relevant Arch Linux bug people do not call a bug](https://bugs.archlinux.org/index.php?do=details&task_id=69563), so oh well!

**Comment by kopp** [comment]
I'll close this as I did not experience more hickups since some time due to this :)
